/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {
  interface AboutSection {}
  interface AppHome {}
  interface AppProfile {
    'match': MatchResults;
  }
  interface AppRoot {}
  interface DlcTerminal {}
  interface MenuButton {}
  interface ProfileImage {}
  interface RrssNavbar {
    'codepenUser': string;
    'githubUser': string;
    'linkedinUser': string;
    'twitterUser': string;
  }
  interface SectionTitle {}
  interface UserName {}
}

declare global {

  // Adding a global JSX for backcompatibility with legacy dependencies
  export namespace JSX {
    export interface Element {}
  }


  interface HTMLAboutSectionElement extends Components.AboutSection, HTMLStencilElement {}
  var HTMLAboutSectionElement: {
    prototype: HTMLAboutSectionElement;
    new (): HTMLAboutSectionElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLDlcTerminalElement extends Components.DlcTerminal, HTMLStencilElement {}
  var HTMLDlcTerminalElement: {
    prototype: HTMLDlcTerminalElement;
    new (): HTMLDlcTerminalElement;
  };

  interface HTMLMenuButtonElement extends Components.MenuButton, HTMLStencilElement {}
  var HTMLMenuButtonElement: {
    prototype: HTMLMenuButtonElement;
    new (): HTMLMenuButtonElement;
  };

  interface HTMLProfileImageElement extends Components.ProfileImage, HTMLStencilElement {}
  var HTMLProfileImageElement: {
    prototype: HTMLProfileImageElement;
    new (): HTMLProfileImageElement;
  };

  interface HTMLRrssNavbarElement extends Components.RrssNavbar, HTMLStencilElement {}
  var HTMLRrssNavbarElement: {
    prototype: HTMLRrssNavbarElement;
    new (): HTMLRrssNavbarElement;
  };

  interface HTMLSectionTitleElement extends Components.SectionTitle, HTMLStencilElement {}
  var HTMLSectionTitleElement: {
    prototype: HTMLSectionTitleElement;
    new (): HTMLSectionTitleElement;
  };

  interface HTMLUserNameElement extends Components.UserName, HTMLStencilElement {}
  var HTMLUserNameElement: {
    prototype: HTMLUserNameElement;
    new (): HTMLUserNameElement;
  };
  interface HTMLElementTagNameMap {
    'about-section': HTMLAboutSectionElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'dlc-terminal': HTMLDlcTerminalElement;
    'menu-button': HTMLMenuButtonElement;
    'profile-image': HTMLProfileImageElement;
    'rrss-navbar': HTMLRrssNavbarElement;
    'section-title': HTMLSectionTitleElement;
    'user-name': HTMLUserNameElement;
  }
}

declare namespace LocalJSX {
  interface AboutSection extends JSXBase.HTMLAttributes<HTMLAboutSectionElement> {}
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppProfile extends JSXBase.HTMLAttributes<HTMLAppProfileElement> {
    'match'?: MatchResults;
  }
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface DlcTerminal extends JSXBase.HTMLAttributes<HTMLDlcTerminalElement> {}
  interface MenuButton extends JSXBase.HTMLAttributes<HTMLMenuButtonElement> {}
  interface ProfileImage extends JSXBase.HTMLAttributes<HTMLProfileImageElement> {}
  interface RrssNavbar extends JSXBase.HTMLAttributes<HTMLRrssNavbarElement> {
    'codepenUser'?: string;
    'githubUser'?: string;
    'linkedinUser'?: string;
    'twitterUser'?: string;
  }
  interface SectionTitle extends JSXBase.HTMLAttributes<HTMLSectionTitleElement> {}
  interface UserName extends JSXBase.HTMLAttributes<HTMLUserNameElement> {}

  interface IntrinsicElements {
    'about-section': AboutSection;
    'app-home': AppHome;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'dlc-terminal': DlcTerminal;
    'menu-button': MenuButton;
    'profile-image': ProfileImage;
    'rrss-navbar': RrssNavbar;
    'section-title': SectionTitle;
    'user-name': UserName;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


